const { v4: uuidv4 } = require('uuid');

const store = {
    users: [
        {
            _id: 'fd225498-517b-45c1-b619-5282e9bf21fb', // ID from logs
            email: 'farmer@test.com',
            password: '$2a$10$YourHashedPasswordHere', // This won't matter for token auth but good for login
            role: 'farmer',
            profile: {
                name: 'Seeded Farmer',
                phone: '1234567890',
                location: { address: 'Farm Road', city: 'Nashik', state: 'Maharashtra' },
                avatar: 'https://via.placeholder.com/150',
                bio: 'I am a seeded farmer for testing.'
            },
            rating: 4.5,
            totalRatings: 10,
            isVerified: true,
            createdAt: new Date()
        }
    ],
    products: [
        {
            _id: uuidv4(),
            farmer: 'fd225498-517b-45c1-b619-5282e9bf21fb',
            title: 'Fresh Organic Tomatoes',
            description: 'Naturally grown, vibrant red tomatoes straight from the farm. Rich in vitamins and perfect for salads and curries.',
            category: 'vegetables',
            images: ['/images/tomato.png'],
            basePrice: 45,
            quantity: 100,
            availableQuantity: 100,
            unit: 'kg',
            availableFrom: new Date(),
            availableTo: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
            deliveryOptions: { pickup: true, delivery: true, deliveryRadius: 10, deliveryFee: 30 },
            location: { address: 'Farm Road', city: 'Nashik', state: 'Maharashtra' },
            organic: true,
            status: 'active',
            views: 0,
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            _id: uuidv4(),
            farmer: 'fd225498-517b-45c1-b619-5282e9bf21fb',
            title: 'Baby Spinach Leaves',
            description: 'Tender baby spinach leaves, harvested fresh daily. Loaded with iron, calcium, and antioxidants.',
            category: 'vegetables',
            images: ['/images/spinach.png'],
            basePrice: 35,
            quantity: 200,
            availableQuantity: 200,
            unit: 'bunch',
            availableFrom: new Date(),
            availableTo: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
            deliveryOptions: { pickup: true, delivery: true, deliveryRadius: 10, deliveryFee: 20 },
            location: { address: 'Green Fields', city: 'Pune', state: 'Maharashtra' },
            organic: true,
            status: 'active',
            views: 0,
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            _id: uuidv4(),
            farmer: 'seed-farmer-3',
            title: 'Alphonso Mangoes',
            description: 'Premium Alphonso mangoes, the king of fruits. Sweet, aromatic, and bursting with tropical flavor.',
            category: 'fruits',
            images: ['/images/mango.png'],
            basePrice: 120,
            quantity: 50,
            availableQuantity: 50,
            unit: 'kg',
            availableFrom: new Date(),
            availableTo: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
            deliveryOptions: { pickup: true, delivery: true, deliveryRadius: 15, deliveryFee: 50 },
            location: { address: 'Coastal Road', city: 'Ratnagiri', state: 'Maharashtra' },
            organic: false,
            status: 'active',
            views: 0,
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            _id: uuidv4(),
            farmer: 'seed-farmer-4',
            title: 'Basmati Rice Premium',
            description: 'Long-grain premium basmati rice with a rich aroma. Perfect for biryanis, pulao, and everyday meals.',
            category: 'grains',
            images: ['/images/rice.png'],
            basePrice: 150,
            quantity: 500,
            availableQuantity: 500,
            unit: 'kg',
            availableFrom: new Date(),
            availableTo: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000),
            deliveryOptions: { pickup: true, delivery: true, deliveryRadius: 20, deliveryFee: 40 },
            location: { address: 'Hill Road', city: 'Dehradun', state: 'Uttarakhand' },
            organic: false,
            status: 'active',
            views: 0,
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            _id: uuidv4(),
            farmer: 'seed-farmer-5',
            title: 'Cow Milk',
            description: 'Pure, pasteurized cow milk delivered fresh from the farm every morning. No added preservatives.',
            category: 'dairy',
            images: ['/images/milk.png'],
            basePrice: 35,
            quantity: 100,
            availableQuantity: 100,
            unit: 'liter',
            availableFrom: new Date(),
            availableTo: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
            deliveryOptions: { pickup: true, delivery: true, deliveryRadius: 5, deliveryFee: 10 },
            location: { address: 'Dairy Lane', city: 'Anand', state: 'Gujarat' },
            organic: true,
            status: 'active',
            views: 0,
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            _id: uuidv4(),
            farmer: 'seed-farmer-6',
            title: 'Wild Forest Honey',
            description: '100% pure wild forest honey, unprocessed and unfiltered. Natural sweetener packed with health benefits.',
            category: 'herbs',
            images: ['/images/honey.png'],
            basePrice: 450,
            quantity: 30,
            availableQuantity: 30,
            unit: 'piece',
            availableFrom: new Date(),
            availableTo: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
            deliveryOptions: { pickup: true, delivery: true, deliveryRadius: 25, deliveryFee: 50 },
            location: { address: 'Forest Area', city: 'Coorg', state: 'Karnataka' },
            organic: true,
            status: 'active',
            views: 0,
            createdAt: new Date(),
            updatedAt: new Date()
        }
    ],
    orders: [],
    chats: [],
    reviews: []
};

module.exports = store;
