const { v4: uuidv4 } = require('uuid');

const store = {
    users: [
        {
            _id: 'fd225498-517b-45c1-b619-5282e9bf21fb', // ID from logs
            email: 'farmer@test.com',
            password: '$2a$10$cVofAncK2ontiDwIDvyMHeIeouyDqBXT3H.Y2Xm6IXwXRYfu6vSdm', // bcrypt hash for 'farmer123'
            role: 'farmer',
            profile: {
                name: 'Seeded Farmer',
                phone: '1234567890',
                location: { address: 'Farm Road', city: 'Nashik', state: 'Maharashtra' },
                avatar: 'https://via.placeholder.com/150',
                bio: 'I am a seeded farmer for testing.'
            },
            rating: 4.5,
            totalRatings: 10,
            isVerified: true,
            createdAt: new Date()
        },
        {
            _id: 'c7b9e0f3-d5a2-4e1b-8c4d-6f2a7e9b1c3d',
            email: 'customer@test.com',
            password: '$2a$10$h3J8/Ox.kNzdjH2BuBsbOeZsA07CQ8TPwvtZipOt.mpIWQQoB0Rxa', // hash for 'customer123'
            role: 'buyer',
            profile: {
                name: 'Test Customer',
                phone: '0987654321',
                location: { address: 'Buyer Lane', city: 'Mumbai', state: 'Maharashtra' },
                avatar: 'https://via.placeholder.com/150',
                bio: 'I am a seeded customer for testing.'
            },
            createdAt: new Date()
        }
    ],
    products: [
        {
            _id: uuidv4(),
            farmer: 'fd225498-517b-45c1-b619-5282e9bf21fb',
            title: 'Fresh Organic Tomatoes',
            description: 'Naturally grown, vibrant red tomatoes straight from the farm. Rich in vitamins and perfect for salads and curries.',
            category: 'vegetables',
            images: ['/images/tomato.png'],
            basePrice: 45,
            quantity: 100,
            availableQuantity: 100,
            unit: 'kg',
            availableFrom: new Date(),
            availableTo: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
            deliveryOptions: { pickup: true, delivery: true, deliveryRadius: 10, deliveryFee: 30 },
            location: { address: 'Farm Road', city: 'Nashik', state: 'Maharashtra' },
            organic: true,
            status: 'active',
            views: 0,
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            _id: uuidv4(),
            farmer: 'fd225498-517b-45c1-b619-5282e9bf21fb',
            title: 'Baby Spinach Leaves',
            description: 'Tender baby spinach leaves, harvested fresh daily. Loaded with iron, calcium, and antioxidants.',
            category: 'vegetables',
            images: ['/images/spinach.png'],
            basePrice: 35,
            quantity: 200,
            availableQuantity: 200,
            unit: 'bunch',
            availableFrom: new Date(),
            availableTo: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
            deliveryOptions: { pickup: true, delivery: true, deliveryRadius: 10, deliveryFee: 20 },
            location: { address: 'Green Fields', city: 'Pune', state: 'Maharashtra' },
            organic: true,
            status: 'active',
            views: 0,
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            _id: uuidv4(),
            farmer: 'fd225498-517b-45c1-b619-5282e9bf21fb',
            title: 'Alphonso Mangoes',
            description: 'Premium Alphonso mangoes, the king of fruits. Sweet, aromatic, and bursting with tropical flavor.',
            category: 'fruits',
            images: ['https://images.unsplash.com/photo-1553279768-865429fa0078?w=400'],
            basePrice: 120,
            quantity: 50,
            availableQuantity: 50,
            unit: 'kg',
            availableFrom: new Date(),
            availableTo: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
            deliveryOptions: { pickup: true, delivery: true, deliveryRadius: 15, deliveryFee: 50 },
            location: { address: 'Farm Road', city: 'Nashik', state: 'Maharashtra' },
            organic: false,
            status: 'active',
            views: 12,
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            _id: uuidv4(),
            farmer: 'fd225498-517b-45c1-b619-5282e9bf21fb',
            title: 'Basmati Rice Premium',
            description: 'Long-grain premium basmati rice with a rich aroma. Perfect for biryanis, pulao, and everyday meals.',
            category: 'grains',
            images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400'],
            basePrice: 150,
            quantity: 500,
            availableQuantity: 500,
            unit: 'kg',
            availableFrom: new Date(),
            availableTo: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000),
            deliveryOptions: { pickup: true, delivery: true, deliveryRadius: 20, deliveryFee: 40 },
            location: { address: 'Farm Road', city: 'Nashik', state: 'Maharashtra' },
            organic: false,
            status: 'active',
            views: 8,
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            _id: uuidv4(),
            farmer: 'fd225498-517b-45c1-b619-5282e9bf21fb',
            title: 'Fresh Cow Milk',
            description: 'Pure, pasteurized cow milk delivered fresh from the farm every morning. No added preservatives.',
            category: 'dairy',
            images: ['https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400'],
            basePrice: 35,
            quantity: 100,
            availableQuantity: 100,
            unit: 'liter',
            availableFrom: new Date(),
            availableTo: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
            deliveryOptions: { pickup: true, delivery: true, deliveryRadius: 5, deliveryFee: 10 },
            location: { address: 'Farm Road', city: 'Nashik', state: 'Maharashtra' },
            organic: true,
            status: 'active',
            views: 22,
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            _id: uuidv4(),
            farmer: 'fd225498-517b-45c1-b619-5282e9bf21fb',
            title: 'Wild Forest Honey',
            description: '100% pure wild forest honey, unprocessed and unfiltered. Natural sweetener packed with health benefits.',
            category: 'herbs',
            images: ['https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400'],
            basePrice: 450,
            quantity: 30,
            availableQuantity: 30,
            unit: 'piece',
            availableFrom: new Date(),
            availableTo: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
            deliveryOptions: { pickup: true, delivery: true, deliveryRadius: 25, deliveryFee: 50 },
            location: { address: 'Farm Road', city: 'Nashik', state: 'Maharashtra' },
            organic: true,
            status: 'active',
            views: 37,
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            _id: uuidv4(),
            farmer: 'fd225498-517b-45c1-b619-5282e9bf21fb',
            title: 'Red Onions',
            description: 'Fresh farm-picked red onions. Crisp, pungent and perfect for everyday Indian cooking.',
            category: 'vegetables',
            images: ['https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=400'],
            basePrice: 28,
            quantity: 300,
            availableQuantity: 300,
            unit: 'kg',
            availableFrom: new Date(),
            availableTo: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
            deliveryOptions: { pickup: true, delivery: false, deliveryRadius: 0, deliveryFee: 0 },
            location: { address: 'Farm Road', city: 'Nashik', state: 'Maharashtra' },
            organic: false,
            status: 'active',
            views: 5,
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            _id: uuidv4(),
            farmer: 'fd225498-517b-45c1-b619-5282e9bf21fb',
            title: 'Green Chillies',
            description: 'Fresh spicy green chillies, handpicked from organic fields. Adds the perfect kick to any dish.',
            category: 'vegetables',
            images: ['https://images.unsplash.com/photo-1571680322279-a226e6a4cc2a?w=400'],
            basePrice: 60,
            quantity: 0,
            availableQuantity: 0,
            unit: 'kg',
            availableFrom: new Date(),
            availableTo: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
            deliveryOptions: { pickup: true, delivery: true, deliveryRadius: 10, deliveryFee: 20 },
            location: { address: 'Farm Road', city: 'Nashik', state: 'Maharashtra' },
            organic: true,
            status: 'sold_out',
            views: 18,
            createdAt: new Date(),
            updatedAt: new Date()
        }
    ],
    orders: [],
    chats: [],
    reviews: []
};

module.exports = store;
